name = Agile Collective hero
description = An Agile Collective theme. 3 column layout with a prominent hero region.
preview = preview.png
template = agile-hero-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/agile-hero/agile-hero.layout.css
stylesheets[all][] = css/layouts/agile-hero/agile-hero.layout.no-query.css
